### ISSUE TITLE
New DIGS_HOME2 global variable

### ISSUE THREAD

**Issue by ulad-litvin** [giffordlabcvr/DIGS-tool#4]
Hi. I've recently updated DIGS to the latest version from GitHub and noticed that a new global variable called DIGS_HOME2 has been introduced. This variable is not mentioned in the DIGS manual, so I just duplicated the path to my DIGS-tool directory to it (the same path that was assigned to the DIGS_HOME) keeping DIGS_HOME unchanged. It looks like DIGS is working fine (apart from the bitscore threshold), so I am flagging this up just in case.

**Comment by robjgiff** [comment]
Thanks for spotting this, it crept in by accident. I use $DIGS_HOME2 as my digs home directory on alpha, separate from digs home directory for general use.
